stages:
 # build
 - test
 - deploy

test:
  image: python:3-alpine
  stage: test
  script:
   - python -m unittest tests

deploy:
  image: python:3-alpine
  stage: deploy
  script:
   - python microblog.py
  after_script:
   - echo "I do something after_script"
  only:
   - master
