jobs:
- job: 'Test'
  pool:
    vmImage: 'ubuntu-16.04' # other options: 'macOS-10.14', 'vs2017-win2016'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'

  steps:
  - checkout: self
    clean: false
    lfs: false
    submodules: recursive
    persistCredentials: true
    
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
  - script: python -m pip install --upgrade pip
    displayName: 'Install tools'    
  - script: pip install -r requirements.txt
    displayName: 'Install requirements'  
  - script: python tests.py
    displayName: 'Run Unittests'
