"""Added Date Fields

Revision ID: 85f8e8edb38d
Revises: c3f3b06dee9d
Create Date: 2020-03-17 11:49:39.145660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f8e8edb38d'
down_revision = 'c3f3b06dee9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('day', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('year', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_event_day'), 'event', ['day'], unique=False)
    op.create_index(op.f('ix_event_month'), 'event', ['month'], unique=False)
    op.create_index(op.f('ix_event_timestamp'), 'event', ['timestamp'], unique=False)
    op.create_index(op.f('ix_event_year'), 'event', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_year'), table_name='event')
    op.drop_index(op.f('ix_event_timestamp'), table_name='event')
    op.drop_index(op.f('ix_event_month'), table_name='event')
    op.drop_index(op.f('ix_event_day'), table_name='event')
    op.drop_column('event', 'year')
    op.drop_column('event', 'month')
    op.drop_column('event', 'day')
    # ### end Alembic commands ###
